### PR TITLE
WIP: Rewrite most of the library.

### PR DESCRIPTION
**Pull request by MrJacz**
Rewrite of the library

### CODE REVIEW

**Comment by resynth1943** [comment]
Try to opt for more descriptive commit names, and avoid sentences that use the past-tense. 

```
Added x
```
Should really be
```
Add x
```

Just a tip :wink:

**Comment by MrJacz** [comment]
@resynth1943 All of my commit messages are actual memes

**Comment by resynth1943** [comment]
Lol. Fair enough, then!

**Comment by TacticalTechJay** [comment]
Well damn. After all those commits and changes and now you guys hit a wall.

**Pull request merged**
