### PR TITLE
Added a check in sendWS to see if the guild still exists.

### PR DESCRIPTION
**Pull request by Deivu**
Fixed the indents for you <3

### CODE REVIEW

**Comment by MrJacz** [comment]
Please do not recreate prs. you can edit code in the previous pr...

**Comment by Deivu** [comment]
@MrJacz I reforked the repo since the last pr was so messy, and edited it in an actual code editor instead

**Comment by Deivu** [comment]
the last pr was mb since I hurried that forgive me for that sempai

**Comment by MrJacz** [comment]
Im going to close this. Reason being that the next release on npm will be v3. so this pr is pointless as its implemented in v3 already.

**Pull request closed without merging**
