### PR TITLE
Update PlayerManager.js

### PR DESCRIPTION
**Pull request by TacticalTechJay**
Added term 'cache' to multiple pieces due to recent change in master branch of discord.js that involves adding cache to nearly everything.

### CODE REVIEW

**Comment by MrJacz** [comment]
While this PR is correct it also removes support for discord.js stable

**Comment by TacticalTechJay** [comment]
I see. Will this mean that discord.js master will eventually be lost from support for this? Or will those who use master have to use a fork with the correction made?

**Comment by withmask** [comment]
@TacticalTechJay I think using this fork for master users would be a good idea, or if Jacz could create a new branch for master and use this fork, that would be even nicer. But yeah to keep support for stable i think using this fork for master and kepping the master branch working with d.js stable

**Review by satoufuyuki — APPROVED** [review]

**Comment by MrJacz** [comment]
#60 closes this

**Pull request closed without merging**
